import "@/app/ui/globals.css";
import type { Metadata } from "next";
import { inter } from "@/app/ui/fonts";
import ThemeProvider from "@/components/theme-provider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	// suppressHydrationWarning (next-theme)
	return (
		<>
			<html lang="fr" suppressHydrationWarning>
				<body className={`${inter.className} antialiased`}>
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange
					>
						{children}
					</ThemeProvider>
				</body>
			</html>
		</>
	);
}
